#!/usr/bin/env bash
apt-get update
apt-get install build-essential libssl-dev git-core
adduser --home /home/nodejs --shell /bin/bash --disabled-password --disabled-login --system nodejs

#as the user, we run the rest of setup process
sudo -i -u nodejs `pwd`/phase2

