#!/usr/bin/env bash

#Install nvm, it handles all the installation for us
git clone git://github.com/creationix/nvm.git ~/.nvm
. ~/.nvm/nvm.sh


#install nodejs
nvm sync
time nvm install latest
nvm use latest

echo -e -n "\n. ~/.nvm/nvm.sh\n" >> ~/.bashrc
echo -e -n "\nnvm use latest\n" >> ~/.bashrc

#Setup npm, this makes life much easier:
mkdir ~/git
cd ~/git
git clone https://github.com/isaacs/npm.git
cd npm/
make install


